mybatis:
    type-aliases-package: com.stephen.myblog.entity

server:
    port: 80
    servlet:
        context-path: /myblog
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root